### ISSUE TITLE
should the `track` call modify `revenue` properties?

### ISSUE THREAD

**Issue by skydivedan** [segment-integrations/analytics-swift-optimizely#10]
Optimizely expects all `revenue` amounts to be represented as in `Int` in cents. But other plugins to Segment don't have this requirement.

Should this plugin convert `revenue` values before calling the `Optimizely` plugin? Or, perhaps have an `init` parameter like `convertRevenueToCents` which would give the caller a way to configure this?

**Comment by alanjcharles** [comment]
Hi @skydivedan - Sorry, I'm not sure I understand exactly.  Is the `revenue` data not being properly recorded in Optimizely? If so, this is definitely something we can look into.

**Comment by skydivedan** [comment]
> Hi @skydivedan - Sorry, I'm not sure I understand exactly. Is the `revenue` data not being properly recorded in Optimizely? If so, this is definitely something we can look into.

Optimizely expects `revenue` values to be in cents, represented as an integer. So, normally when I send events to Segment, the `revenue` value starts off (in my app) as a Decimal value. And it gets sent off to Segment that way. But in the app, when I catch the event in `track`, before I send it to Optimizely, I need to multiply the value by 100 and send it along to Optimizely.

There are places on Optimizely's website where it talks about wanting `revenue` values in cents: 
- https://docs.developers.optimizely.com/experimentation-data/docs/event-api-troubleshooting#i-sent-events-with-revenue-values-through-the-api-but-the-revenue-is-not-calculated-correctly-on-the-results-page
- https://docs.developers.optimizely.com/full-stack-experimentation/docs/include-event-tags#reserved-tag-keys

Other services don't want it in cents, but Optimizely does. So, it would seem appropriate to have this plugin modify the value to be an int.

**Comment by alanjcharles** [comment]
got it, thanks. Will prioritize it asap
