### ISSUE TITLE
Can the `OptimizelyClient` get passed back after initialization, or setup?

### ISSUE THREAD

**Issue by skydivedan** [segment-integrations/analytics-swift-optimizely#7]
I'm currently using Optimizely in my iOS project, to control whether certain features are surfaced (or hidden) in my app. So I make calls to the `OptimizelyClient` like `isFeatureEnabled` or `getFeatureVariableString`.

Since `analytics-swift-optimizely` actually instantiates an `OptimizelyClient`, it would be nice if that client was either passed back, or otherwise made available to the caller. Right now it's `private`, and I don't understand why.

For an example of what I'm talking about, the [`BrazeDestination`](https://github.com/braze-inc/braze-segment-swift/blob/main/Sources/SegmentBraze/BrazeDestination.swift) for Segment has a callback in it's `init` routine, which will get called after the `Braze` instance is instantiated from the data from Segment. It passes the instance of `Braze` in the caller, allowing the caller to perform extra configuration.

In the Optimizely case, it could pass back an `OptimizelyClient`, and then I could use that client to do regular Optimizely things, like get the state of various feature flags. But right now, I'd need to create a new instance of `OptimizelyClient` -- which I'd rather not do.

Just wondering if this is anything that is being considered in an update.

**Comment by alanjcharles** [comment]
Hi @skydivedan thanks for bringing this to our attention. A fix is available in `1.1.1` please let us know if you run into any other issues. Thanks!
